# paksa TLP jalan
TLP_ENABLE=1

# Governor Powersave untuk efisiensi
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

# Mengatur kebijakan energi (EPP)
CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power

# batasi turbo boost
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

# Active State Power Management
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersupersave

# Mematikan MX450 saat idle
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto

# Hemat daya SSD NVMe
AHCI_RUNTIME_PM_ON_AC=on
AHCI_RUNTIME_PM_ON_BAT=auto
